#pragma once
#ifndef THIRD_PARTY_DECLARATIONS_H
#define THIRD_PARTY_DECLARATIONS_H

#define VMA_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION
#define VK_USE_PLATFORM_WIN32_KHR
#define GLM_FORCE_DEFAULT_ALIGNED_GENTYPES
#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEPTH_ZERO_TO_ONE

#endif